title: 'DataShift'
description: 'Документация по продукту DataShift'
markdown: 'kramdown'
remote_theme: 'just-the-docs/just-the-docs'
plugins:
  - 'jekyll-seo-tag'

# Укажите базовый путь, если сайт публикуется как /<repo>/
# Например, если ваш репозиторий называется datashift:
baseurl: '/datashift'
url: 'https://zamasskin.github.io'

# Локализация
lang: 'ru'

exclude:
  - 'node_modules'
  - 'vendor'
  - 'tests'
  - 'test-results'

# Just the Docs settings
search_enabled: true
color_scheme: 'dark'
aux_links:
  'GitHub': 'https://github.com/zamasskin/datashift'
